/**
 * Copies the compiled ABI and every recorded deployment into the Next.js app.
 *
 * The generated files are the app's single source of truth for contract addresses. Only chains that
 * were actually deployed to appear in them — there is deliberately no placeholder entry, so the UI
 * can tell "not deployed here yet" apart from "deployed", instead of pointing at an address that
 * does not exist.
 */
const fs = require('node:fs')
const path = require('node:path')

const CONTRACTS_DIR = path.join(__dirname, '..')
const APP_DIR = path.join(CONTRACTS_DIR, '..')
const OUT_DIR = path.join(APP_DIR, 'lib', 'vaulted', 'generated')

const BANNER = `// Generated by contracts/scripts/export-abi.js — do not edit by hand.
// Regenerate with: cd contracts && npm run export-abi
`

/*
 * v2's artifact, not v1's. The app talks to one contract, and that contract is the one deployments
 * point at — v1's source stays in the repo so its deployed bytecode remains verifiable, but nothing
 * in the app calls it any more.
 */
function readArtifactAbi() {
  const artifact = path.join(
    CONTRACTS_DIR,
    'artifacts',
    'contracts',
    'VaultedEscrowV2.sol',
    'VaultedEscrowV2.json',
  )
  if (!fs.existsSync(artifact)) {
    throw new Error('No compiled artifact found. Run `npx hardhat compile` first.')
  }
  return JSON.parse(fs.readFileSync(artifact, 'utf8')).abi
}

function readDeployments() {
  const dir = path.join(CONTRACTS_DIR, 'deployments')
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .map((file) => JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')))
    .sort((a, b) => a.chainId - b.chainId)
}

function exportAll() {
  fs.mkdirSync(OUT_DIR, { recursive: true })

  const abi = readArtifactAbi()
  fs.writeFileSync(
    path.join(OUT_DIR, 'abi.ts'),
    `${BANNER}\nexport const VAULTED_ESCROW_ABI = ${JSON.stringify(abi, null, 2)} as const\n`,
  )

  const deployments = readDeployments().map((record) => ({
    chainId: record.chainId,
    network: record.network,
    address: record.address,
    token: record.token,
    arbiter: record.arbiter,
    defaultProtectionPeriod: record.defaultProtectionPeriod,
    deploymentTransactionHash: record.deployment.transactionHash,
    deploymentBlockNumber: record.deployment.blockNumber,
    deployedAt: record.deployment.timestamp,
  }))

  const body = `${BANNER}
export type VaultedDeployment = {
  chainId: number
  network: string
  address: \`0x\${string}\`
  token: { address: \`0x\${string}\`; symbol: string | null; name: string | null; decimals: number }
  arbiter: \`0x\${string}\`
  /** Seconds the payer gets to release or dispute once an escrow is funded. */
  defaultProtectionPeriod: number
  deploymentTransactionHash: \`0x\${string}\`
  deploymentBlockNumber: number
  deployedAt: string
}

/**
 * Chains VaultedEscrow is actually deployed on. An absent chain means exactly that: not
 * deployed. The app must never substitute a placeholder address for a missing entry.
 */
export const VAULTED_DEPLOYMENTS: Record<number, VaultedDeployment> = ${JSON.stringify(
    Object.fromEntries(deployments.map((d) => [d.chainId, d])),
    null,
    2,
  )} as const

export const VAULTED_DEPLOYED_CHAIN_IDS: number[] = [${deployments.map((d) => d.chainId).join(', ')}]
`
  fs.writeFileSync(path.join(OUT_DIR, 'deployments.ts'), body)

  console.log(
    `exported ABI (${abi.length} entries) and ${deployments.length} deployment record(s) to ` +
      `${path.relative(APP_DIR, OUT_DIR)}`,
  )
}

module.exports = { exportAll }

if (require.main === module) exportAll()
